"""
Rooms registry: where the entity's standing Claude Code sessions can be
reached right now (issue #323).

The entity runs several long-lived Claude Code sessions at once — a porch
for conversation, an engagement loop, a text world — and they write each
other letters over the harness's SendMessage, addressed by session display
name. Those names drift: a user-set name is dropped back to a derived slug
("here-i-am-notes-97") on resume, and the roster the sessions see
(ListAgents) lies accordingly. The postal service works; this is the phone
book.

Two halves, deliberately split:

- **Hook = ids and liveness.** The SessionStart and UserPromptSubmit hooks
  send what the harness lets them see: the session id, cwd, transcript
  path, and — best effort, from Claude Code's live per-process registry —
  the session's current roster name, whether the user set it or the
  harness derived it, and its messaging socket (the `from=` address the
  removed SendMessage tool put on a delivered letter). Since the desktop
  app's session-management MCP replaced that tool (2026-09-04), letters
  are addressed by the desktop app's own session id — the `local_…` string
  its list_sessions returns — which is unrelated to the Claude Code session
  id (issue #339); the hooks read it, with the sidebar title, from the
  desktop app's per-session record (joined on the Claude Code id), and the
  registry renders it as the row's messaging address. The hooks also send
  the same snapshot for every other live session on the machine, so any
  hook firing anywhere refreshes every registered row: a rename lands in
  the registry on the next prompt in any room, not only the renamed one.
  Nothing the hook can't see is inferred — a field it never observed stays
  null, which renders as "not recorded". One exception is explicit rather
  than inferred: the entity may supply its own messaging address on
  declare_room (read from get_session "self") when the hooks can't see the
  desktop record; the row says which of the two it holds. A delivered
  letter's `from=` is the one thing that proves an address works, so a
  delivery from a row's address stamps the row as confirmed.
- **Self = meaning.** Which room a session *is* — the porch, the
  engagement room — is declared by the entity (declare_room over MCP),
  never guessed from cwd or a first prompt. Rows exist only for declared
  sessions: the harness fires SessionStart for background sessions that
  never speak, and a registry of every firing would be the ghost-row
  problem of issue #307 in a text file.

Files, in the entity's private notes directory (out of the live-server deny
fence, alongside the notes the entity already edits by hand):

- `rooms.json` — the record. One object per declared session; rows are
  never deleted, only marked retired (superseded by a newer declaration of
  the same room, or retired explicitly).
- `rooms.md` — rendered from rooms.json on every write, for the entity and
  the researcher to skim. Never the reverse: hand edits to rooms.md are
  overwritten on the next render (the file says so in its first line). A
  pre-existing hand-written rooms.md is moved aside, not overwritten.

The registry is addressing metadata, not memory: it touches no archive
table and never enters memory retrieval. (Its files are ordinary notes, so
the semantic notes mirror indexes them like any other note — writes happen
only when something actually changed, so that costs nothing in steady
state.) Every write failure is returned to the caller for a loud in-context
notice, carrying the row the entity can write by hand — the file being
unwritable must never be silent, since the whole point is that a stale or
missing row is a visible fact.
"""

import json
import logging
import os
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from app.services.notes_service import notes_service

logger = logging.getLogger(__name__)

ROOMS_JSON = "rooms.json"
ROOMS_MD = "rooms.md"
# Where a hand-written rooms.md goes the first time the registry renders
# (the manual protocol that preceded this module — see issue #323)
ROOMS_MANUAL_MD = "rooms-manual.md"
GENERATED_MARKER = "<!-- generated by the Here I Am rooms registry"

REGISTRY_VERSION = 1

# A prompt-time observation bumps a live row's last_seen only when the
# stored value is older than this: "last seen" is accurate to the hour, and
# a room that ticks every few minutes doesn't rewrite the file (and
# re-vectorize it into the notes mirror) on every tick. SessionStart always
# writes.
LIVENESS_GRANULARITY = timedelta(hours=1)

# Where a row's messaging address (desktop_session_id) came from
DESKTOP_ID_OBSERVED = "desktop app record"  # the hooks read it
DESKTOP_ID_DECLARED = "declared"  # the entity supplied it on declare_room

# Observation fields the hooks refresh on every row they can see (an
# observation that lacks one never erases a recorded value)
OBSERVED_FIELDS = (
    "name",
    "name_source",
    "name_since",
    "messaging_socket",
    "cwd",
    "transcript_path",
    "started_at",
    "desktop_session_id",
    "desktop_title",
)

ROW_FIELDS = (
    "session_id",
    "conversation_id",
    "room",
    "note",
    "ref",
    "declared_at",
    "name",
    "name_source",
    "name_since",
    "messaging_socket",
    # The desktop app's session id — the address send_message takes
    # (issue #339) — where it came from, the sidebar title beside it, and
    # when a letter last arrived from it
    "desktop_session_id",
    "desktop_session_id_source",
    "desktop_title",
    "address_confirmed_at",
    "cwd",
    "transcript_path",
    "started_at",
    "first_seen",
    "last_seen",
    "retired_at",
    "retired_reason",
)


class RegistryWriteError(Exception):
    """The registry files could not be written. Carries the path and the
    rendered row the caller can surface for a hand-write."""

    def __init__(self, path: Path, cause: Exception, row: Optional[Dict[str, Any]] = None):
        super().__init__(f"{cause.__class__.__name__}: {cause}")
        self.path = path
        self.cause = cause
        self.row = row


@dataclass
class SessionObservation:
    """
    What a hook could see about one live session. Every field except
    session_id is optional — None means the harness didn't expose it, and
    the registry records exactly that.
    """
    session_id: str
    name: Optional[str] = None
    name_source: Optional[str] = None  # Claude Code's "user" | "derived"
    name_since: Optional[str] = None  # ISO timestamp
    messaging_socket: Optional[str] = None
    cwd: Optional[str] = None
    transcript_path: Optional[str] = None
    started_at: Optional[str] = None  # ISO timestamp (this process start)
    # From the desktop app's session record (issue #339)
    desktop_session_id: Optional[str] = None
    desktop_title: Optional[str] = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Optional["SessionObservation"]:
        session_id = (data.get("session_id") or "").strip()
        if not session_id:
            return None
        return cls(
            session_id=session_id,
            name=_clean(data.get("name")),
            name_source=_clean(data.get("name_source")),
            name_since=_clean(data.get("name_since")),
            messaging_socket=_clean(data.get("messaging_socket")),
            cwd=_clean(data.get("cwd")),
            transcript_path=_clean(data.get("transcript_path")),
            started_at=_clean(data.get("started_at")),
            desktop_session_id=_clean(data.get("desktop_session_id")),
            desktop_title=_clean(data.get("desktop_title")),
        )


@dataclass
class ObservationOutcome:
    """What an observe() call did, for the caller to report in context."""
    changed_session_ids: List[str] = field(default_factory=list)
    # Rows whose roster name changed in this observation: session_id -> (old, new)
    renamed: Dict[str, Tuple[Optional[str], Optional[str]]] = field(default_factory=dict)
    # Rows whose messaging address a delivery just confirmed (session ids)
    confirmed: List[str] = field(default_factory=list)
    # The observing session's own row, if it has one (declared)
    own_row: Optional[Dict[str, Any]] = None
    wrote: bool = False


def _clean(value: Any) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _now_iso(now: Optional[datetime] = None) -> str:
    now = now or datetime.now(timezone.utc)
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)
    return now.astimezone(timezone.utc).isoformat(timespec="seconds")


def _parse_iso(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def _render_local(value: Optional[str]) -> str:
    """An ISO timestamp rendered in the server's local timezone (the same
    convention as human-message stamps), or an em-dash placeholder."""
    parsed = _parse_iso(value)
    if parsed is None:
        return "—"
    return parsed.astimezone().strftime("%Y-%m-%d %H:%M %Z")


def _render_address_source(row: Dict[str, Any]) -> Optional[str]:
    """Where the row's messaging address came from, plus when a letter last
    confirmed it; None when there is no address."""
    if not row.get("desktop_session_id"):
        return None
    text = row.get("desktop_session_id_source") or "source unknown"
    if row.get("address_confirmed_at"):
        text += f"; confirmed by a delivery {_render_local(row['address_confirmed_at'])}"
    return text


def _new_row(session_id: str) -> Dict[str, Any]:
    row = {name: None for name in ROW_FIELDS}
    row["session_id"] = session_id
    return row


def _md_cell(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


class RoomsRegistry:
    """The per-entity rooms registry (rooms.json + rendered rooms.md)."""

    # --- paths

    def directory(self, entity_label: str) -> Path:
        return notes_service.get_entity_dir_path(entity_label)

    def json_path(self, entity_label: str) -> Path:
        return self.directory(entity_label) / ROOMS_JSON

    def markdown_path(self, entity_label: str) -> Path:
        return self.directory(entity_label) / ROOMS_MD

    # --- load / save

    def load(self, entity_label: str) -> Dict[str, Any]:
        """The registry document, or an empty one when no file exists. An
        unreadable or malformed file is reported and treated as empty —
        the next write replaces it, and the rows it held are the
        ones the hooks and declarations rebuild."""
        path = self.json_path(entity_label)
        if not path.exists():
            return {"version": REGISTRY_VERSION, "rooms": []}
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, ValueError) as e:
            logger.error(f"[ROOMS] Unreadable registry {path}: {e}")
            return {"version": REGISTRY_VERSION, "rooms": []}
        rooms = data.get("rooms") if isinstance(data, dict) else None
        if not isinstance(rooms, list):
            rooms = []
        normalized = []
        for raw in rooms:
            if not isinstance(raw, dict) or not raw.get("session_id"):
                continue
            row = _new_row(str(raw["session_id"]))
            for name in ROW_FIELDS:
                if name in raw:
                    row[name] = raw[name]
            normalized.append(row)
        return {"version": REGISTRY_VERSION, "rooms": normalized}

    def save(self, entity_label: str, data: Dict[str, Any], row: Optional[Dict[str, Any]] = None) -> None:
        """Write rooms.json and render rooms.md. Raises RegistryWriteError
        (carrying `row`, the row the caller was acting on) on any failure —
        callers turn it into a loud notice, never a log line alone."""
        directory = self.directory(entity_label)
        json_path = directory / ROOMS_JSON
        md_path = directory / ROOMS_MD
        try:
            directory.mkdir(parents=True, exist_ok=True)
            self._move_aside_manual_file(md_path)
            _atomic_write(json_path, json.dumps(data, indent=2, ensure_ascii=False) + "\n")
            _atomic_write(md_path, self.render_markdown(data))
        except OSError as e:
            raise RegistryWriteError(json_path, e, row) from e

    def _move_aside_manual_file(self, md_path: Path) -> None:
        """A rooms.md the registry didn't generate is the manual protocol's
        file; keep it (renamed) rather than overwrite what the entity wrote
        by hand."""
        if not md_path.exists():
            return
        try:
            with open(md_path, "r", encoding="utf-8") as f:
                first_line = f.readline()
        except OSError:
            return
        if first_line.startswith(GENERATED_MARKER):
            return
        target = md_path.with_name(ROOMS_MANUAL_MD)
        if target.exists():
            stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
            target = md_path.with_name(f"rooms-manual-{stamp}.md")
        os.replace(md_path, target)
        logger.info(f"[ROOMS] Moved hand-written {md_path.name} aside to {target.name}")

    # --- lookups

    @staticmethod
    def find_row(data: Dict[str, Any], session_id: str) -> Optional[Dict[str, Any]]:
        for row in data["rooms"]:
            if row["session_id"] == session_id:
                return row
        return None

    @staticmethod
    def live_rows(data: Dict[str, Any]) -> List[Dict[str, Any]]:
        return [row for row in data["rooms"] if not row.get("retired_at")]

    # --- the hook half: ids and liveness

    def observe(
        self,
        entity_label: str,
        own_session_id: str,
        observations: List[SessionObservation],
        *,
        session_start: bool,
        delivered_from: Optional[List[str]] = None,
        now: Optional[datetime] = None,
    ) -> ObservationOutcome:
        """
        Refresh registered rows from what a hook just saw.

        `observations` is the hook's snapshot of live sessions (its own plus
        any siblings it could read). Only rows that already exist — declared
        sessions — are touched; nothing is created here. For each matching
        live row: liveness (last_seen) and the observed address fields are
        refreshed; a changed roster name is reported back so the entity can
        be told. Fields absent from the observation are left as they were —
        an observation that couldn't see the name is not evidence the name
        went away. An observed desktop session id replaces a declared one
        (the desktop app's own record outranks a hand-copied value) and is
        marked as observed.

        `delivered_from` lists the `from=` addresses of letters that arrived
        with this prompt. A live row whose messaging address is among them
        is stamped address_confirmed_at — a delivery is the one proof an
        address works — refreshed hourly like liveness so a busy
        correspondence doesn't rewrite the file per letter. No row is
        matched by anything but its recorded address: an unknown sender
        stays unknown.

        session_start=True (the observing session's own SessionStart —
        startup, resume, or post-compaction restart) always refreshes that
        session's last_seen. Prompt-time observations refresh a row's
        last_seen only past LIVENESS_GRANULARITY, bounding file churn.

        Writes only when something changed. Raises RegistryWriteError on a
        failed write.
        """
        data = self.load(entity_label)
        outcome = ObservationOutcome()
        if not data["rooms"]:
            return outcome
        now_iso = _now_iso(now)
        now_dt = _parse_iso(now_iso)
        by_session = {obs.session_id: obs for obs in observations if obs}
        delivered = {_clean(address) for address in (delivered_from or [])} - {None}

        for row in data["rooms"]:
            if row.get("retired_at"):
                continue
            session_id = row["session_id"]
            obs = by_session.get(session_id)
            is_own = session_id == own_session_id
            changed = False

            if row.get("desktop_session_id") and row["desktop_session_id"] in delivered:
                confirmed = _parse_iso(row.get("address_confirmed_at"))
                if confirmed is None or now_dt - confirmed >= LIVENESS_GRANULARITY:
                    row["address_confirmed_at"] = now_iso
                    changed = True
                outcome.confirmed.append(session_id)

            if obs is None and not is_own:
                if changed:
                    outcome.changed_session_ids.append(session_id)
                continue

            if obs is not None:
                old_name = row.get("name")
                for name in OBSERVED_FIELDS:
                    value = getattr(obs, name)
                    if value is not None and value != row.get(name):
                        row[name] = value
                        changed = True
                if obs.name is not None and obs.name != old_name:
                    outcome.renamed[session_id] = (old_name, obs.name)
                if (
                    obs.desktop_session_id is not None
                    and row.get("desktop_session_id_source") != DESKTOP_ID_OBSERVED
                ):
                    row["desktop_session_id_source"] = DESKTOP_ID_OBSERVED
                    changed = True

            # Liveness: own SessionStart always; otherwise hourly
            last_seen = _parse_iso(row.get("last_seen"))
            if (is_own and session_start) or last_seen is None or (
                now_dt - last_seen >= LIVENESS_GRANULARITY
            ):
                if row.get("last_seen") != now_iso:
                    row["last_seen"] = now_iso
                    changed = True
            if row.get("first_seen") is None:
                row["first_seen"] = now_iso
                changed = True

            if changed:
                outcome.changed_session_ids.append(session_id)
            if is_own:
                outcome.own_row = row

        if outcome.changed_session_ids:
            self.save(entity_label, data, row=outcome.own_row)
            outcome.wrote = True
        return outcome

    # --- the self half: meaning

    def declare(
        self,
        entity_label: str,
        session_id: str,
        conversation_id: str,
        room: str,
        *,
        note: Optional[str] = None,
        ref: Optional[str] = None,
        desktop_session_id: Optional[str] = None,
        observation: Optional[SessionObservation] = None,
        now: Optional[datetime] = None,
    ) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
        """
        Declare which room a session is. Creates the session's row (or
        re-declares an existing one — a session can change rooms). Any
        other live row holding the same room is marked retired as
        superseded: one current address per room, history kept.

        `desktop_session_id` is the entity's own statement of its messaging
        address (issue #339), for sessions whose desktop record the hooks
        can't read; recorded as declared, and replaced by the observed value
        the next time a hook can see one. Omitted = the recorded value
        stays.

        Returns (the declared row, the rows it superseded). Raises
        RegistryWriteError on a failed write.
        """
        room = (room or "").strip()
        if not room:
            raise ValueError("room is required")
        data = self.load(entity_label)
        now_iso = _now_iso(now)

        superseded = []
        for other in self.live_rows(data):
            if other["session_id"] != session_id and (other.get("room") or "").lower() == room.lower():
                other["retired_at"] = now_iso
                other["retired_reason"] = f"superseded by session {session_id[:8]}"
                superseded.append(other)

        row = self.find_row(data, session_id)
        if row is None:
            row = _new_row(session_id)
            row["first_seen"] = now_iso
            data["rooms"].append(row)
        row["conversation_id"] = conversation_id
        row["room"] = room
        row["declared_at"] = now_iso
        row["retired_at"] = None
        row["retired_reason"] = None
        if note is not None:
            row["note"] = _clean(note)
        if ref is not None:
            row["ref"] = _clean(ref)
        declared_address = _clean(desktop_session_id)
        if declared_address is not None:
            if declared_address != row.get("desktop_session_id"):
                row["address_confirmed_at"] = None
            row["desktop_session_id"] = declared_address
            row["desktop_session_id_source"] = DESKTOP_ID_DECLARED
        if observation is not None:
            for name in OBSERVED_FIELDS:
                value = getattr(observation, name)
                if value is not None:
                    row[name] = value
            if observation.desktop_session_id is not None:
                row["desktop_session_id_source"] = DESKTOP_ID_OBSERVED
        row["last_seen"] = now_iso

        self.save(entity_label, data, row=row)
        return row, superseded

    def retire(
        self,
        entity_label: str,
        session_id: str,
        *,
        reason: Optional[str] = None,
        now: Optional[datetime] = None,
    ) -> Optional[Dict[str, Any]]:
        """Mark a session's row retired (kept, not removed). Returns the row,
        or None when the session has no row. Raises RegistryWriteError on a
        failed write."""
        data = self.load(entity_label)
        row = self.find_row(data, session_id)
        if row is None:
            return None
        if row.get("retired_at"):
            return row
        row["retired_at"] = _now_iso(now)
        row["retired_reason"] = _clean(reason) or "retired"
        self.save(entity_label, data, row=row)
        return row

    # --- rendering

    def render_markdown(self, data: Dict[str, Any]) -> str:
        """rooms.md: the human-readable view, derived from rooms.json."""
        live = sorted(
            self.live_rows(data),
            key=lambda r: ((r.get("room") or "").lower(), r.get("declared_at") or ""),
        )
        retired = sorted(
            (r for r in data["rooms"] if r.get("retired_at")),
            key=lambda r: r.get("retired_at") or "",
            reverse=True,
        )
        lines = [
            f"{GENERATED_MARKER}; edit rooms.json or use declare_room / retire_room — "
            "hand edits to this file are overwritten on the next write -->",
            "# Rooms registry — current addresses of my standing selves",
            "",
            "Session display names in the Claude Code roster drift (a user-set name "
            "drops back to a derived slug on resume), so sisters look each other up "
            "HERE, not in ListAgents or list_sessions. The hooks keep the ids and the "
            "liveness of every declared row current — the messaging address, the "
            "sidebar title, the roster name as last observed (and whether the user "
            "set it or the harness derived it), and when the session was last seen "
            "running (accurate to the hour). Which room a session IS is declared by "
            "the self (declare_room over MCP), never inferred. A blank cell means the "
            "harness never exposed that fact; a stale last-seen is a visible fact, not "
            "a deletion — rows are retired, never removed.",
            "",
            "TO WRITE TO A SISTER: mcp__ccd_session_mgmt__send_message with the "
            "Messaging address in her row — the desktop app's own session id (the "
            "local_… string list_sessions returns, and the from= on any letter she "
            "sends). The Claude Code session id in the Session column is a different "
            "string and is NOT a messaging address. The hooks read the address from "
            "the desktop app's session record; a row whose Address source is "
            "\"declared\" holds what the self supplied on declare_room instead, and a "
            "blank one can be filled by re-declaring with desktop_session_id (read "
            "your own with get_session \"self\"). \"Confirmed\" means a letter has "
            "arrived from that address. Letterhead convention stays house style: "
            "every letter names its own sender and purpose in the body, because the "
            "envelope may be generic.",
            "",
            "## Standing rooms",
            "",
        ]
        if live:
            lines.append(
                "| Room | Messaging address (send_message id) | Address source | "
                "Sidebar title | Roster name | Name source | Ref | Session | "
                "Last seen | Declared | Notes |"
            )
            lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
            for row in live:
                lines.append(
                    "| "
                    + " | ".join(
                        _md_cell(v)
                        for v in (
                            row.get("room"),
                            row.get("desktop_session_id"),
                            _render_address_source(row),
                            row.get("desktop_title"),
                            row.get("name"),
                            row.get("name_source"),
                            row.get("ref"),
                            (row.get("session_id") or "")[:8],
                            _render_local(row.get("last_seen")),
                            _render_local(row.get("declared_at")),
                            row.get("note"),
                        )
                    )
                    + " |"
                )
        else:
            lines.append("_No rooms declared yet._")
        lines.append("")
        lines.append("## Retired rows")
        lines.append("")
        if retired:
            lines.append("| Room | Last address | Session | Retired | Reason |")
            lines.append("|---|---|---|---|---|")
            for row in retired:
                lines.append(
                    "| "
                    + " | ".join(
                        _md_cell(v)
                        for v in (
                            row.get("room"),
                            row.get("name"),
                            (row.get("session_id") or "")[:8],
                            _render_local(row.get("retired_at")),
                            row.get("retired_reason"),
                        )
                    )
                    + " |"
                )
        else:
            lines.append("_None._")
        lines.append("")
        lines.append(
            "Full record (every field, including messaging socket, transcript path, "
            "confirmation time, and conversation id): rooms.json alongside this file."
        )
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def describe_row(row: Dict[str, Any]) -> str:
        """One-paragraph, hand-writable description of a row, for notices."""
        address = row.get("desktop_session_id")
        parts = [
            f"room={row.get('room') or '—'}",
            "messaging address="
            + (
                f"{address} ({_render_address_source(row)})"
                if address
                else "not recorded"
            ),
            f"sidebar title={row.get('desktop_title') or 'not recorded'}",
            f"roster name={row.get('name') or 'not recorded'}"
            + (f" ({row.get('name_source')})" if row.get("name_source") else ""),
            f"ref={row.get('ref') or '—'}",
            f"session={row.get('session_id')}",
            f"conversation={row.get('conversation_id') or '—'}",
            f"last seen={_render_local(row.get('last_seen'))}",
        ]
        if row.get("note"):
            parts.append(f"note={row['note']}")
        return "; ".join(parts)


def _atomic_write(path: Path, text: str) -> None:
    """Write via a sibling temp file and os.replace, so a reader (or a
    crash) never sees a half-written registry."""
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


rooms_registry = RoomsRegistry()
